name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

        name: Install dependencies
      - run: |
          pip install -r requirements.txt

      - run: python ./code-appli-python/vote/app.py

      - name: Create artifact
        run: |
          zip -r app.zip .

      - uses: actions/upload-artifact@v2
        with:
          name: app.zip
          path: app.zip
